<?php

/**
 * @file ds_tokens.module
 * Provides additional tokens integration to the DS field UI.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ds_tokens_form_field_ui_display_overview_form_alter(&$form, &$form_state) {
  if (module_exists('ds')) {
    // Hook in our process function which changes the form descriptions about
    // tokenized data.
    $form['#process'][] = 'ds_tokens_ds_attributes_token';
  }
}

/**
 * Implements hook_theme_registry_alter().
 *
 * @see _ds_theme_registry_alter().
 */
function ds_tokens_theme_registry_alter(&$theme_registry) {

  // Inject ds_entity_variables in all entity theming functions.
  $entity_info = entity_get_info();
  foreach ($entity_info as $entity => $info) {
    if (isset($entity_info[$entity]['fieldable']) && $entity_info[$entity]['fieldable']) {

      // User uses user_profile for theming.
      if ($entity == 'user') $entity = 'user_profile';

      // Only add preprocess functions if entity exposes theme function.
      if (isset($theme_registry[$entity])) {
        $theme_registry[$entity]['preprocess functions'][] = 'ds_tokens_token_variables';
      }
    }
  }

  // Support for File Entity.
  if (isset($theme_registry['file_entity'])) {
    $theme_registry['file_entity']['preprocess functions'][] = 'ds_tokens_token_variables';
  }

  // Support for Entity API.
  if (isset($theme_registry['entity'])) {
    $theme_registry['entity']['preprocess functions'][] = 'ds_tokens_token_variables';
  }
}

/**
 * Tokenize the altered data.
 */
function ds_tokens_token_variables(&$variables) {
  if (!empty($variables['layout_attributes'])) {
    $entity_type = $variables['elements']['#entity_type'];
    switch ($entity_type) {
      case 'taxonomy_term':
        $entity = $variables['term'];
        break;
      default:
        $entity = $variables[$entity_type];

    }
    $variables['layout_attributes'] = token_replace($variables['layout_attributes'], array($entity_type => $entity));
  }
}

/**
 * Alter the field UI to show the user tokens can now be used in layout attributes.
 */
function ds_tokens_ds_attributes_token($form) {
  if (isset($form['additional_settings']['region_wrapper'])) {
    $form['additional_settings']['region_wrapper']['layout_attributes']['#description'] = t('E.g. role="navigation" (tokens are available)');
    // Always display the tokens list, not only when the link settings are
    // configured for it.
    unset($form['additional_settings']['region_wrapper']['tokens']['#states']);
  }
  return $form;
}
